apiVersion: apps/v1
kind: Deployment
metadata: 
  name: news-web-app-deploy
  labels:
    app: news-web-app-app
spec:
  selector:
    matchLabels:
      app: news-web-app-app
  replicas: 2      
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  template:
    metadata:
      labels:
        app: news-web-app-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: news-web-app-app
        image: my-py-image:0.0.1
        imagePullPolicy: "Never"        
        ports: 
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"    