apiVersion: v1
kind: Service
metadata:
  name: news-web-app-service
spec:
  type: NodePort
  selector:
    app: news-web-app-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000